/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package game.logic.navmeshpathfinding;

import collision.Figure;
import engine.utilities.Point;
import engine.utilities.PointContainer;
import game.logic.navmeshpathfinding.navigationmesh.*;

import javax.swing.*;
import java.awt.*;
import java.util.ArrayList;
import java.util.Set;

import static engine.utilities.Methods.roundDouble;

/**
 * @author WROBELP1
 */
public class Window extends javax.swing.JFrame {

    NavigationMesh mesh;
    Point end, start, correction, mob, prey, colS, colE;
    Point[] destination;
    Point[] polygon = new Point[4];
    ArrayList<Line> lines;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;

    /**
     * Creates new form Window
     */
    public Window() {
        initComponents();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed"
        // desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase
         * /tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Window().setVisible(true);
            }
        });
    }

    public void addVariables(NavigationMesh mesh, Point end, Point start, PointContainer path) {
        this.mesh = mesh;
        if (end != null)
            this.end = new Point(end.getX(), end.getY());
        if (start != null)
            this.start = new Point(start.getX(), start.getY());
        if (path != null) {
            Point[] npath = new Point[path.size()];
            for (int i = 0; i < path.size(); i++) {
                npath[i] = new Point(path.get(i).getX(), path.get(i).getY());
            }
            this.destination = npath;
        }
    }

    public void setCorrection(Point correct, int x, int y, Figure inAWay) {
        if (correct == null || inAWay == null) {
            correction = colS = colE = null;
            return;
        }
        correction = new Point(correct.getX() - x, correct.getY() - y);
        colS = new Point(inAWay.getX() - x, inAWay.getY() - y);
        colE = new Point(inAWay.getXEnd() - x, inAWay.getYEnd() - y);
    }

    public void setPositions(Point prey, Point mob, int x, int y) {
        this.prey = new Point(prey.getX() - x, prey.getY() - y);
        this.mob = new Point(mob.getX() - x, mob.getY() - y);
    }

    public void setEnd(Point end, int x, int y) {
        this.end = new Point(end.getX() - x, end.getY() - y);
    }

    public void setPoly(Polygon poly, int x, int y) {
        if (poly != null) {
            for (int i = 0; i < poly.npoints; i++) {
                polygon[i] = new Point(poly.xpoints[i] - x, poly.ypoints[i] - y);
            }
        }
    }

    public void setNote(String title) {
        setTitle(title);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed"
    // desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new GPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setFocusTraversalPolicyProvider(true);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 1044, Short.MAX_VALUE));
        jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 660, Short.MAX_VALUE));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(
                jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
        layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(
                jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void setLines(Set<Line> lines) {
        ArrayList<Line> temp = new ArrayList<>();
        for (Line l : lines) {
            temp.add(new Line(new Point(l.getStart()), new Point(l.getEnd())));
        }
        this.lines = temp;
    }

    // End of variables declaration//GEN-END:variables
    class GPanel extends JPanel {

        public GPanel() {
        }

        @Override
        public void paintComponent(Graphics g) {
            super.paintComponent(g);
            Graphics2D g2;
            g2 = (Graphics2D) g;
            double SCALE = 0.5;
            Polygon poly = new Polygon();
            if (mesh != null) {
                for (Triangle triangle : mesh.getTriangles()) {
                    for (int j = 0; j < 3; j++) {
                        Node nd = triangle.getNode(j);
                        poly.addPoint(roundDouble(nd.getX() * SCALE), roundDouble(nd.getY() * SCALE));
                    }
                    g2.setColor(Color.lightGray);
                    g2.fill(poly);
                    g2.setColor(Color.gray);
                    g2.draw(poly);
                    poly.reset();
//                    for (int i = 0; i < triangle.getConnectionsNumber(); i++) {
//                        Connection c = triangle.getConnection(i);
//                        g2.setColor(Color.orange);
//                        Node n = c.getNode(0);
//                        g2.fillOval(roundDouble(n.getX() * SCALE - 3), roundDouble(n.getY() * SCALE - 3), 6, 6);
//                        n = c.getNode(1);
//                        g2.fillOval(roundDouble(n.getX() * SCALE - 3), roundDouble(n.getY() * SCALE - 3), 6, 6);
//                    }

                }
                g2.setColor(Color.BLACK);
                for (Bound line : mesh.getBounds()) {
                    g2.drawLine(roundDouble(line.getStart().getX() * SCALE),
                            roundDouble(line.getStart().getY() * SCALE), roundDouble(line.getEnd().getX() * SCALE),
                            roundDouble(line.getEnd().getY() * SCALE));
                }
//            } else if (lines != null) {
//                ArrayList<Line> temp = lines;
//                g2.setColor(Color.BLACK);
//                for (Line line : temp) {
//                    g2.drawLine(roundDouble(line.getStart().getX() * SCALE),
//                            roundDouble(line.getStart().getY() * SCALE), roundDouble(line.getEnd().getX() * SCALE),
//                            roundDouble(line.getEnd().getY() * SCALE));
//                }
            }
            g2.setColor(Color.yellow);
            if (destination != null) {
                for (int i = 0; i < destination.length - 1; i++) {
                    g2.drawLine(roundDouble(destination[i].getX() * SCALE), roundDouble(destination[i].getY()
                                    * SCALE), roundDouble(destination[i + 1].getX() * SCALE),
                            roundDouble(destination[i + 1].getY() * SCALE));
                }
            }

            if (colS != null && colE != null) {
                g2.setColor(Color.BLUE);
                g2.drawLine(roundDouble(colS.getX() * SCALE), roundDouble(colS.getY() * SCALE),
                        roundDouble(colS.getX() * SCALE), roundDouble(colE.getY() * SCALE));
                g2.drawLine(roundDouble(colE.getX() * SCALE), roundDouble(colE.getY() * SCALE),
                        roundDouble(colS.getX() * SCALE), roundDouble(colE.getY() * SCALE));
                g2.drawLine(roundDouble(colE.getX() * SCALE), roundDouble(colE.getY() * SCALE),
                        roundDouble(colE.getX() * SCALE), roundDouble(colS.getY() * SCALE));
                g2.drawLine(roundDouble(colS.getX() * SCALE), roundDouble(colS.getY() * SCALE),
                        roundDouble(colE.getX() * SCALE), roundDouble(colS.getY() * SCALE));
            }

            if (polygon[0] != null && polygon[1] != null && polygon[2] != null && polygon[3] != null) {
                g2.setColor(Color.MAGENTA);
                g2.drawLine(roundDouble(polygon[0].getX() * SCALE), roundDouble(polygon[0].getY() * SCALE),
                        roundDouble(polygon[1].getX() * SCALE), roundDouble(polygon[1].getY() * SCALE));
                g2.drawLine(roundDouble(polygon[1].getX() * SCALE), roundDouble(polygon[1].getY() * SCALE),
                        roundDouble(polygon[2].getX() * SCALE), roundDouble(polygon[2].getY() * SCALE));
                g2.drawLine(roundDouble(polygon[2].getX() * SCALE), roundDouble(polygon[2].getY() * SCALE),
                        roundDouble(polygon[3].getX() * SCALE), roundDouble(polygon[3].getY() * SCALE));
                g2.drawLine(roundDouble(polygon[3].getX() * SCALE), roundDouble(polygon[3].getY() * SCALE),
                        roundDouble(polygon[0].getX() * SCALE), roundDouble(polygon[0].getY() * SCALE));
            }

            if (end != null) {
                g2.setColor(Color.green);
                g2.fillOval(roundDouble(end.getX() * SCALE - 3), roundDouble(end.getY() * SCALE - 3), 6, 6);
            }
            if (start != null) {
                g2.setColor(Color.red);
                g2.fillOval(roundDouble(start.getX() * SCALE - 3), roundDouble(start.getY() * SCALE - 3), 6, 6);
            }
            if (correction != null) {
                g2.setColor(Color.BLUE);
                g2.fillOval(roundDouble(correction.getX() * SCALE - 3), roundDouble(correction.getY() * SCALE - 3),
                        6, 6);
            }

            if (prey != null) {
                g2.setColor(Color.cyan);
                g2.fillOval(roundDouble(prey.getX() * SCALE - 3), roundDouble(prey.getY() * SCALE - 3), 6, 6);
            }

            if (mob != null) {
                g2.setColor(Color.ORANGE);
                g2.fillOval(roundDouble(mob.getX() * SCALE - 3), roundDouble(mob.getY() * SCALE - 3), 6, 6);
            }

            repaint();
        }
    }
}
