/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gameDesigner;

import java.io.File;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Wojtek
 */
public class PathFinder extends javax.swing.JFrame {

    private SpriteLoader cel;
    private int mode;

    public PathFinder(SpriteLoader cel, File dir, int mode) {   // mode : 0 - wszytanie obrazka, 1 - "wyjście" zapisywanych plików, 2 - wczytanie zapisanej tekstury
        initComponents();
        this.cel = cel;
        FilesFC.setCurrentDirectory(dir);
        cel.setEnabled(false);
        FileNameExtensionFilter filter;
        this.mode = mode;
        switch (mode) {
            case 0:
                FilesFC.setFileSelectionMode(javax.swing.JFileChooser.FILES_ONLY);
                filter = new FileNameExtensionFilter(
                        "PNG files", "png");
                FilesFC.setFileFilter(filter);
                break;
            case 1:
                FilesFC.setFileSelectionMode(javax.swing.JFileChooser.DIRECTORIES_ONLY);
                break;
            case 2: 
                FilesFC.setFileSelectionMode(javax.swing.JFileChooser.FILES_ONLY);
                filter = new FileNameExtensionFilter(
                        "Textures (.spr)", "spr");
                FilesFC.setFileFilter(filter);
                break;
        }
    }

    @Override
    public void dispose() {
        cel.setEnabled(true);
        super.dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FilesFC = new javax.swing.JFileChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        FilesFC.setFont(new java.awt.Font("GulimChe", 0, 13)); // NOI18N
        FilesFC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FilesFCActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FilesFC, javax.swing.GroupLayout.DEFAULT_SIZE, 702, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FilesFC, javax.swing.GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FilesFCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FilesFCActionPerformed
        if (evt.getActionCommand().equals("ApproveSelection")) {
            switch (mode) {
                case 0:
                    cel.setImg(FilesFC.getSelectedFile());
                    cel.ostDir(FilesFC.getCurrentDirectory());
                    break;
                case 1:
                    cel.setOutput(FilesFC.getSelectedFile());
                    break;
                case 2:
                    cel.openTex(FilesFC.getSelectedFile());
                    break;                    
            }
            this.dispose();
        }
        if (evt.getActionCommand().equals("CancelSelection")) {
            this.dispose();
        }
    }//GEN-LAST:event_FilesFCActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFileChooser FilesFC;
    // End of variables declaration//GEN-END:variables
}
